---

- name: Run cfg commands on routers
  hosts: R1
  gather_facts: false
  
  tasks:
  
  - name: Apply ACL CFG
    ios_config:
      src: acl_cfg.txt
    register: cfg

  - name: Show config updates
    debug: 
      var: cfg.updates
    when: cfg.changed
