---

- name: Run show command on routers
  hosts: cisco-routers
  gather_facts: false
  
  tasks:
  
  - name: sh arp command
    ios_command:
      commands: 
      - sh arp
      - sh ip int br
    register: result
    
  - debug: 
      var: result.stdout_lines
